---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo
  labels:
    app: todo
    app.kubernetes.io/instance: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo
        deployment: todo
    spec:
      volumes:
        - name: todo-config
          configMap:
            name: todo-config
            defaultMode: 420
      containers:
        - name: todo
          image: 'quay.io/kahlai/todo:v1'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: todo-config
              readOnly: true
              mountPath: /work/config/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---

kind: ConfigMap
apiVersion: v1
metadata:
  name: todo-config
data:
  application.properties: |-
    quarkus.datasource.db-kind=postgresql 
    quarkus.datasource.username=todo
    quarkus.datasource.password=todo

    quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/todo
    quarkus.datasource.jdbc.max-size=16
    quarkus.hibernate-orm.database.generation=drop-and-create
    #quarkus.hibernate-orm.database.generation=update


---

kind: Service
apiVersion: v1
metadata:
  name: todo
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: todo
    deployment: todo

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: todo
spec:
  to:
    kind: Service
    name: todo
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None